/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.BeMusic;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author pjman
 */
public class loginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginFrame.class.getName());

    /**
     * Creates new form loginFrame
     */
    public loginFrame() {
        this.setLocationRelativeTo(null);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        usernamefield = new javax.swing.JTextField();
        welcomelabel = new javax.swing.JLabel();
        enterlabel = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setForeground(new java.awt.Color(242, 242, 242));

        usernamefield.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        welcomelabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        welcomelabel.setText("Welcome to BeMusic");

        enterlabel.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        enterlabel.setText("Enter your username to log in:");

        imagelabel.setText("aiuh");

        confirm.setText("Confirm");
        confirm.addActionListener(this::confirmActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomelabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterlabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirm)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(welcomelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterlabel)
                    .addComponent(confirm))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        String user = usernamefield.getText();
        if (user.equals("test")){
            TimelineFrame timelineframe = new TimelineFrame(user);
            timelineframe.setVisible(true);
            setVisible(false);
        }
        else {
            System.out.println(user);
            JOptionPane.showMessageDialog(this, "Please log in with a valid username.");
            
        }
    }                                       

    public void loading(){
        try {
        URL url = new URL("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSPZ9qXGkUUKotCwh3A5cIFzDd3O-HdRRUNw&s"); // Replace with your image URL
        Image image = ImageIO.read(url);
        // Use the image, for example, in a JLabel
        Image resized = image.getScaledInstance(250,250,Image.SCALE_DEFAULT);
        imagelabel.setIcon(new ImageIcon(resized));
        // Add label to your JFrame or JPanel
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    
    public static void bootUp(){
        loginFrame login = new loginFrame();
        login.loading();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginFrame().setVisible(true));

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        bootUp();
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton confirm;
    private javax.swing.JLabel enterlabel;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JLabel welcomelabel;
    // End of variables declaration                   
}
