/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.BeMusic;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author pjman
 */
public class loginFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginFrame.class.getName());
    private static BeMusicDatabase database;

    /**
     * Creates new form loginFrame
     */
    public loginFrame(BeMusicDatabase database) {
        this.setLocationRelativeTo(null);
        loginFrame.database = database;
        System.out.println("CREATED LOG IN. DATABASE: " + database);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        welcomelabel = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        usernamefield = new javax.swing.JTextField();
        enterlabel = new javax.swing.JLabel();
        enterlabel1 = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setForeground(new java.awt.Color(242, 242, 242));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        welcomelabel.setBackground(new java.awt.Color(204, 204, 0));
        welcomelabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        welcomelabel.setForeground(new java.awt.Color(204, 204, 0));
        welcomelabel.setText("Welcome to BeMusic!");

        confirm.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        confirm.setText("Confirm");
        confirm.addActionListener(this::confirmActionPerformed);

        usernamefield.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        usernamefield.setSelectionColor(new java.awt.Color(204, 204, 0));

        enterlabel.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        enterlabel.setForeground(new java.awt.Color(255, 255, 255));
        enterlabel.setText("Enter your username to log in.");

        enterlabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        enterlabel1.setForeground(new java.awt.Color(255, 255, 255));
        enterlabel1.setText("Username");

        imagelabel.setForeground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(welcomelabel)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirm, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(enterlabel1)
                                .addGap(37, 37, 37)
                                .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(enterlabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(welcomelabel)
                .addGap(18, 18, 18)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(enterlabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enterlabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirm)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        String user = usernamefield.getText();
        String[] users = {"pj", "PJ", "Alyssa", "Cris", "Jo", "Emma", "Ethan", "Andrea", "Aniyah",
            "Hansel", "Hasseit", "Vanessa", "Nelson", "Amri", "Tomy", "Gwyn", "Carmen", "Lili", "Julia", "Liz",
            "Kieran", "Maela", "Rhea", "Jaden", "Aami"};
        ArrayList<String> usersarray = new ArrayList<>(Arrays.asList(users));

        if (usersarray.contains(user)){

            System.out.println("LOGGED IN. DATABASE: " + database);
            
            TimelineFrame.setup(user, database);
            setVisible(false);
        }
        else {
            System.out.println(user);
            JOptionPane.showMessageDialog(this, "Please log in with a valid username.", "LOG IN ATTEMPT FAILED",2);
            
        }
    }//GEN-LAST:event_confirmActionPerformed

    public void loading(){
        try {
        URL url = new URL("https://i.pinimg.com/originals/98/7c/92/987c925021ab888257cf75194d761bc9.gif"); // Replace with your image URL
        Image image = ImageIO.read(url);
        Image resized = image.getScaledInstance(150,150,Image.SCALE_DEFAULT);
        imagelabel.setIcon(new ImageIcon(resized));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    
    public static void bootUp(BeMusicDatabase database){
        loginFrame login = new loginFrame(database);
        login.loading();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> login.setVisible(true));

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        bootUp(database);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JLabel enterlabel;
    private javax.swing.JLabel enterlabel1;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usernamefield;
    private javax.swing.JLabel welcomelabel;
    // End of variables declaration//GEN-END:variables
}
