/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.BeMusic;

/**
 *
 * @author pjman
 */
public class ProfileFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProfileFrame.class.getName());

    /**
     * Creates new form ProfileFrame
     */
    public ProfileFrame() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        calendarpanel = new javax.swing.JPanel();
        day1 = new javax.swing.JLabel();
        day2 = new javax.swing.JLabel();
        day3 = new javax.swing.JLabel();
        day4 = new javax.swing.JLabel();
        day5 = new javax.swing.JLabel();
        day6 = new javax.swing.JLabel();
        day7 = new javax.swing.JLabel();
        day8 = new javax.swing.JLabel();
        day9 = new javax.swing.JLabel();
        day10 = new javax.swing.JLabel();
        day11 = new javax.swing.JLabel();
        day12 = new javax.swing.JLabel();
        day13 = new javax.swing.JLabel();
        day14 = new javax.swing.JLabel();
        day15 = new javax.swing.JLabel();
        day16 = new javax.swing.JLabel();
        day17 = new javax.swing.JLabel();
        day18 = new javax.swing.JLabel();
        day19 = new javax.swing.JLabel();
        day20 = new javax.swing.JLabel();
        day21 = new javax.swing.JLabel();
        day22 = new javax.swing.JLabel();
        day23 = new javax.swing.JLabel();
        day24 = new javax.swing.JLabel();
        day25 = new javax.swing.JLabel();
        day26 = new javax.swing.JLabel();
        day27 = new javax.swing.JLabel();
        day28 = new javax.swing.JLabel();
        day29 = new javax.swing.JLabel();
        day30 = new javax.swing.JLabel();
        day31 = new javax.swing.JLabel();
        ratingpanel = new javax.swing.JPanel();
        ratinglabel = new javax.swing.JLabel();
        greetinglabel = new javax.swing.JLabel();
        toolbar = new javax.swing.JPanel();
        timelinebutton = new javax.swing.JButton();
        profilelabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calendarpanel.setBackground(new java.awt.Color(0, 0, 0));

        day1.setBackground(new java.awt.Color(255, 51, 51));
        day1.setForeground(new java.awt.Color(102, 102, 102));
        day1.setText("AAAAAAAAAAAAAA");
        day1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day2.setBackground(new java.awt.Color(255, 51, 51));
        day2.setForeground(new java.awt.Color(102, 102, 102));
        day2.setText("AAAAAAAAAA\\nA");
        day2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day3.setBackground(new java.awt.Color(255, 51, 51));
        day3.setForeground(new java.awt.Color(102, 102, 102));
        day3.setText("AAAAAAAAAAAAAA");
        day3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day4.setBackground(new java.awt.Color(255, 51, 51));
        day4.setForeground(new java.awt.Color(102, 102, 102));
        day4.setText("AAAAAAAAAA\\nA");
        day4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day5.setBackground(new java.awt.Color(255, 51, 51));
        day5.setForeground(new java.awt.Color(102, 102, 102));
        day5.setText("AAAAAAAAAAAAAA");
        day5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day6.setBackground(new java.awt.Color(255, 51, 51));
        day6.setForeground(new java.awt.Color(102, 102, 102));
        day6.setText("AAAAAAAAAA\\nA");
        day6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day7.setBackground(new java.awt.Color(255, 51, 51));
        day7.setForeground(new java.awt.Color(102, 102, 102));
        day7.setText("AAAAAAAAAA\\nA");
        day7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day8.setBackground(new java.awt.Color(255, 51, 51));
        day8.setForeground(new java.awt.Color(102, 102, 102));
        day8.setText("AAAAAAAAAA\\nA");
        day8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day9.setBackground(new java.awt.Color(255, 51, 51));
        day9.setForeground(new java.awt.Color(102, 102, 102));
        day9.setText("AAAAAAAAAA\\nA");
        day9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day10.setBackground(new java.awt.Color(255, 51, 51));
        day10.setForeground(new java.awt.Color(102, 102, 102));
        day10.setText("AAAAAAAAAA\\nA");
        day10.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day11.setBackground(new java.awt.Color(255, 51, 51));
        day11.setForeground(new java.awt.Color(102, 102, 102));
        day11.setText("AAAAAAAAAA\\nA");
        day11.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day12.setBackground(new java.awt.Color(255, 51, 51));
        day12.setForeground(new java.awt.Color(102, 102, 102));
        day12.setText("AAAAAAAAAA\\nA");
        day12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day13.setBackground(new java.awt.Color(255, 51, 51));
        day13.setForeground(new java.awt.Color(102, 102, 102));
        day13.setText("AAAAAAAAAA\\nA");
        day13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day14.setBackground(new java.awt.Color(255, 51, 51));
        day14.setForeground(new java.awt.Color(102, 102, 102));
        day14.setText("AAAAAAAAAA\\nA");
        day14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day15.setBackground(new java.awt.Color(255, 51, 51));
        day15.setForeground(new java.awt.Color(102, 102, 102));
        day15.setText("AAAAAAAAAAAAAA");
        day15.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day16.setBackground(new java.awt.Color(255, 51, 51));
        day16.setForeground(new java.awt.Color(102, 102, 102));
        day16.setText("AAAAAAAAAA\\nA");
        day16.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day17.setBackground(new java.awt.Color(255, 51, 51));
        day17.setForeground(new java.awt.Color(102, 102, 102));
        day17.setText("AAAAAAAAAAAAAA");
        day17.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day18.setBackground(new java.awt.Color(255, 51, 51));
        day18.setForeground(new java.awt.Color(102, 102, 102));
        day18.setText("AAAAAAAAAA\\nA");
        day18.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day19.setBackground(new java.awt.Color(255, 51, 51));
        day19.setForeground(new java.awt.Color(102, 102, 102));
        day19.setText("AAAAAAAAAAAAAA");
        day19.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day20.setBackground(new java.awt.Color(255, 51, 51));
        day20.setForeground(new java.awt.Color(102, 102, 102));
        day20.setText("AAAAAAAAAA\\nA");
        day20.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day21.setBackground(new java.awt.Color(255, 51, 51));
        day21.setForeground(new java.awt.Color(102, 102, 102));
        day21.setText("AAAAAAAAAA\\nA");
        day21.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day22.setBackground(new java.awt.Color(255, 51, 51));
        day22.setForeground(new java.awt.Color(102, 102, 102));
        day22.setText("AAAAAAAAAA\\nA");
        day22.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day23.setBackground(new java.awt.Color(255, 51, 51));
        day23.setForeground(new java.awt.Color(102, 102, 102));
        day23.setText("AAAAAAAAAA\\nA");
        day23.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day24.setBackground(new java.awt.Color(255, 51, 51));
        day24.setForeground(new java.awt.Color(102, 102, 102));
        day24.setText("AAAAAAAAAA\\nA");
        day24.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day25.setBackground(new java.awt.Color(255, 51, 51));
        day25.setForeground(new java.awt.Color(102, 102, 102));
        day25.setText("AAAAAAAAAA\\nA");
        day25.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day26.setBackground(new java.awt.Color(255, 51, 51));
        day26.setForeground(new java.awt.Color(102, 102, 102));
        day26.setText("AAAAAAAAAA\\nA");
        day26.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day27.setBackground(new java.awt.Color(255, 51, 51));
        day27.setForeground(new java.awt.Color(102, 102, 102));
        day27.setText("AAAAAAAAAA\\nA");
        day27.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day28.setBackground(new java.awt.Color(255, 51, 51));
        day28.setForeground(new java.awt.Color(102, 102, 102));
        day28.setText("AAAAAAAAAA\\nA");
        day28.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day29.setBackground(new java.awt.Color(255, 51, 51));
        day29.setForeground(new java.awt.Color(102, 102, 102));
        day29.setText("AAAAAAAAAAAAAA");
        day29.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day30.setBackground(new java.awt.Color(255, 51, 51));
        day30.setForeground(new java.awt.Color(102, 102, 102));
        day30.setText("AAAAAAAAAA\\nA");
        day30.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        day31.setBackground(new java.awt.Color(255, 51, 51));
        day31.setForeground(new java.awt.Color(102, 102, 102));
        day31.setText("AAAAAAAAAAAAAA");
        day31.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout calendarpanelLayout = new javax.swing.GroupLayout(calendarpanel);
        calendarpanel.setLayout(calendarpanelLayout);
        calendarpanelLayout.setHorizontalGroup(
            calendarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calendarpanelLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(calendarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calendarpanelLayout.createSequentialGroup()
                        .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calendarpanelLayout.createSequentialGroup()
                        .addComponent(day8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calendarpanelLayout.createSequentialGroup()
                        .addComponent(day15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calendarpanelLayout.createSequentialGroup()
                        .addComponent(day22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day26, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day27, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(calendarpanelLayout.createSequentialGroup()
                        .addComponent(day29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day30, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(day31, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        calendarpanelLayout.setVerticalGroup(
            calendarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calendarpanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(calendarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(calendarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(calendarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day16, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day20, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day21, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(calendarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day22, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day23, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day24, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day25, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day26, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day27, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day28, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(calendarpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day29, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day30, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(day31, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        ratingpanel.setBackground(new java.awt.Color(102, 102, 102));

        ratinglabel.setBackground(new java.awt.Color(255, 255, 255));
        ratinglabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        ratinglabel.setForeground(new java.awt.Color(255, 255, 255));
        ratinglabel.setText("Your overall BeMusic rating: [RATING]");

        greetinglabel.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        greetinglabel.setForeground(new java.awt.Color(255, 255, 255));
        greetinglabel.setText("Hello, [USERNAME] !");

        javax.swing.GroupLayout ratingpanelLayout = new javax.swing.GroupLayout(ratingpanel);
        ratingpanel.setLayout(ratingpanelLayout);
        ratingpanelLayout.setHorizontalGroup(
            ratingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ratingpanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ratingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(greetinglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratinglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        ratingpanelLayout.setVerticalGroup(
            ratingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ratingpanelLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(greetinglabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ratinglabel)
                .addGap(16, 16, 16))
        );

        toolbar.setBackground(new java.awt.Color(153, 204, 0));

        timelinebutton.setText("Return to Timeline");
        timelinebutton.addActionListener(this::timelinebuttonActionPerformed);

        profilelabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        profilelabel.setText("Your Profile");

        javax.swing.GroupLayout toolbarLayout = new javax.swing.GroupLayout(toolbar);
        toolbar.setLayout(toolbarLayout);
        toolbarLayout.setHorizontalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(profilelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(timelinebutton)
                .addContainerGap())
        );
        toolbarLayout.setVerticalGroup(
            toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(toolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timelinebutton)
                    .addComponent(profilelabel))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratingpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(calendarpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ratingpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(calendarpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timelinebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timelinebuttonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_timelinebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProfileFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel calendarpanel;
    private javax.swing.JLabel day1;
    private javax.swing.JLabel day10;
    private javax.swing.JLabel day11;
    private javax.swing.JLabel day12;
    private javax.swing.JLabel day13;
    private javax.swing.JLabel day14;
    private javax.swing.JLabel day15;
    private javax.swing.JLabel day16;
    private javax.swing.JLabel day17;
    private javax.swing.JLabel day18;
    private javax.swing.JLabel day19;
    private javax.swing.JLabel day2;
    private javax.swing.JLabel day20;
    private javax.swing.JLabel day21;
    private javax.swing.JLabel day22;
    private javax.swing.JLabel day23;
    private javax.swing.JLabel day24;
    private javax.swing.JLabel day25;
    private javax.swing.JLabel day26;
    private javax.swing.JLabel day27;
    private javax.swing.JLabel day28;
    private javax.swing.JLabel day29;
    private javax.swing.JLabel day3;
    private javax.swing.JLabel day30;
    private javax.swing.JLabel day31;
    private javax.swing.JLabel day4;
    private javax.swing.JLabel day5;
    private javax.swing.JLabel day6;
    private javax.swing.JLabel day7;
    private javax.swing.JLabel day8;
    private javax.swing.JLabel day9;
    private javax.swing.JLabel greetinglabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel profilelabel;
    private javax.swing.JLabel ratinglabel;
    private javax.swing.JPanel ratingpanel;
    private javax.swing.JButton timelinebutton;
    private javax.swing.JPanel toolbar;
    // End of variables declaration//GEN-END:variables
}
