/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.BeMusic;


import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.net.URL;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.lang.StringBuilder;

/**
 *
 * @author pjman
 */
public class TimelineFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TimelineFrame.class.getName());
    ArrayList<String[]> history = new ArrayList<String[]>();
    private int index;
    private String currentDate; //index 0
    private String currentUsername; //index 1
    private String currentSongTitle; //index 2
    private String currentArtist; // index 3
    private String imageUrl; // index 4
    private static  String loggedUserStr;
    private static BeMusicDatabase database;

     /**
     * Creates new form TimelineFrame
     */
    public TimelineFrame(String loggedUserStr) {
        System.out.println("new Timeline Frame");
        setLoggedUserStr(loggedUserStr);
        setDatabase(database);
        System.out.println("init:" + loggedUserStr);

        initComponents(loggedUserStr);
    }
    
    /**
     * Updates all current song variables depending on indexing in song timeline array.
     * @param i
     * @return Song
     */
    public String[] getInfo(int i){
        String[] song = history.get(i);
        this.currentDate = song[0];
        this.currentUsername = song[1];
        this.currentSongTitle = song[2];
        this.currentArtist = song[3];
        this.imageUrl = song[4];
        return song;
    }
    
   

    /**
     * Adds song entry (in form of strings) to history (song timeline array).
     * @param date
     * @param username
     * @param songtitle
     * @param artist
     * @param url
     */
    // TODO: MAY END UP UNUSED. MAYBE REMOVE?
    public void addEntry(String date, String username, String songtitle, String artist, String url){
        String[] entry = {date, username,songtitle,artist,url};
        this.history.add(entry);
    }


    // --------------- GETTERS AND SETTERS ---------------
    public void setDatabase(BeMusicDatabase database){
        TimelineFrame.database = database;
    }

    public BeMusicDatabase getDatabase(){
        return database;
    }
    
    public void changeIndex(int var){
        index = index + var;
    }

    public static String getLoggedUserStr(){
        return loggedUserStr;
    }

    public void setLoggedUserStr(String user){
        TimelineFrame.loggedUserStr = user;
    }

    
    public int getIndex(){
        return index;
    }
    
    public ArrayList<String[]> getHistory() {
        return history;
    }

    public void setHistory(ArrayList<String[]> history) {
        this.history = history;
    }

    public String getCurrentDate() {
        return currentDate;
    }

    public void setCurrentDate(String currentDate) {
        this.currentDate = currentDate;
    }

    public String getCurrentUsername() {
        return currentUsername;
    }

    public void setCurrentUsername(String currentUsername) {
        this.currentUsername = currentUsername;
    }

    public String getCurrentSongTitle() {
        return currentSongTitle;
    }

    public void setCurrentSongTitle(String currentSongTitle) {
        this.currentSongTitle = currentSongTitle;
    }

    public String getCurrentArtist() {
        return currentArtist;
    }

    public void setCurrentArtist(String currentArtist) {
        this.currentArtist = currentArtist;
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String user) {

        toolbarPanel = new javax.swing.JPanel();
        timelineLabel = new javax.swing.JLabel();
        profileButton = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        songdisplay = new javax.swing.JPanel();
        songtitlelabel = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();
        artistlabel = new javax.swing.JLabel();
        dateplayedlabel = new javax.swing.JLabel();
        userlistenedtext = new javax.swing.JLabel();
        nextbutton = new javax.swing.JButton();
        lastbutton = new javax.swing.JButton();
        ratesongbutton = new javax.swing.JButton();
        nichebutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolbarPanel.setBackground(new java.awt.Color(153, 204, 0));

        timelineLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        timelineLabel.setText(loggedUserStr +  "'s Timeline");

        profileButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        profileButton.setText("View Profiles");
        profileButton.addActionListener(this::profileButtonActionPerformed);

        javax.swing.GroupLayout toolbarPanelLayout = new javax.swing.GroupLayout(toolbarPanel);
        toolbarPanel.setLayout(toolbarPanelLayout);
        toolbarPanelLayout.setHorizontalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolbarPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(timelineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(profileButton)
                .addGap(14, 14, 14))
        );
        toolbarPanelLayout.setVerticalGroup(
            toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolbarPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(toolbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timelineLabel)
                    .addComponent(profileButton))
                .addGap(12, 12, 12))
        );

        bodyPanel.setBackground(new java.awt.Color(0, 0, 0));
        bodyPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        songdisplay.setBackground(new java.awt.Color(102, 102, 102));

        songtitlelabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        songtitlelabel.setText("SONG TITLE");

        imagelabel.setForeground(new java.awt.Color(255, 51, 51));

        artistlabel.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        artistlabel.setText("Artist Name");

        javax.swing.GroupLayout songdisplayLayout = new javax.swing.GroupLayout(songdisplay);
        songdisplay.setLayout(songdisplayLayout);
        songdisplayLayout.setHorizontalGroup(
            songdisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(songdisplayLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(songdisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(songtitlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(artistlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(songdisplayLayout.createSequentialGroup()
                        .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        songdisplayLayout.setVerticalGroup(
            songdisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, songdisplayLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(artistlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(songtitlelabel)
                .addGap(21, 21, 21))
        );

        dateplayedlabel.setBackground(new java.awt.Color(255, 255, 255));
        dateplayedlabel.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        dateplayedlabel.setForeground(new java.awt.Color(255, 255, 255));
        dateplayedlabel.setText("On DATE PLAYED,");

        userlistenedtext.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userlistenedtext.setForeground(new java.awt.Color(255, 255, 255));
        userlistenedtext.setText("[USERNAME] listened to...");

        nextbutton.setBackground(new java.awt.Color(255, 255, 51));
        nextbutton.setText("->");
        nextbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        nextbutton.addActionListener(this::nextbuttonActionPerformed);

        lastbutton.setBackground(new java.awt.Color(255, 255, 51));
        lastbutton.setText("<-");
        lastbutton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        lastbutton.addActionListener(this::lastbuttonActionPerformed);

        ratesongbutton.setBackground(new java.awt.Color(255, 204, 0));
        ratesongbutton.setText("Rate this song!");
        ratesongbutton.addActionListener(this::ratesongbuttonActionPerformed);

        nichebutton.setBackground(new java.awt.Color(255, 204, 51));
        nichebutton.setText("How niche is it?");
        nichebutton.addActionListener(this::nichebuttonActionPerformed);

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateplayedlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                            .addComponent(userlistenedtext, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(81, 81, 81))
                        .addGroup(bodyPanelLayout.createSequentialGroup()
                            .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(bodyPanelLayout.createSequentialGroup()
                                    .addComponent(lastbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(ratesongbutton)
                                    .addGap(18, 18, 18)
                                    .addComponent(nichebutton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nextbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(songdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(96, 96, 96)))))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(dateplayedlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userlistenedtext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(songdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ratesongbutton)
                    .addComponent(nextbutton)
                    .addComponent(lastbutton)
                    .addComponent(nichebutton))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    

    /**
     * Creates dialog box, allowing user to choose to either view own profile or profile of the user 
     * whose the listened to song is currently being displayed in TimelineFrame.
     * @param evt
     */
    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
        Object[] options = { "Your own", currentUsername};
        int choice = JOptionPane.showOptionDialog(
            null, // Parent component (null means center on screen)
            "Whose profile would you like to view?", // Message to display
            "Profiles", // Dialog title
            JOptionPane.YES_NO_OPTION, // Option type (Yes, No, Cancel)
            JOptionPane.QUESTION_MESSAGE, // Message type (question icon)
            null, // Custom icon (null means no custom icon)
            options, // Custom options array
            options[0] // Initial selection (default is "Cancel")
        );
        
        // Check the user's choice and display profile accordingly
        if (choice == JOptionPane.YES_OPTION) {
            //if user chose 'your profile' / yes option
            ProfileFrame profileframe = new ProfileFrame(loggedUserStr, database); 
            profileframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            profileframe.setVisible(true);
        }
        else if (choice == JOptionPane.NO_OPTION) {
            // If the user chose 'No' aka current profile
            ProfileFrame profileframe = new ProfileFrame(currentUsername,database);
            profileframe.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            profileframe.setVisible(true);
        }
    }//GEN-LAST:event_profileButtonActionPerformed

    /**
     * clicks to view next song. increments index in order to view next in list of song timeline.
     * @param evt
     */
    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        if (index < history.size() -1) {
            changeIndex(1);
        }
        reload(getDatabase());
    }//GEN-LAST:event_nextbuttonActionPerformed

    /**
     * clicks to view previous song. decrement index in order to view previous in list of song timeline.
     * @param evt
     */
    private void lastbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastbuttonActionPerformed
        if (index >=1){
            changeIndex(-1);
        }
        
        reload(getDatabase());
    } //GEN-LAST:event_lastbuttonActionPerformed

    /**
     * Action that occurs after clicking rate button. Allows user to rate a song, 
     * which adds to the listening user's overall rating.
     * @param evt
     */
    private void ratesongbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratesongbuttonActionPerformed
        StringBuilder sb = new StringBuilder("How do you feel about");
        sb.append("\n").append(currentSongTitle).append(" by ").append(currentArtist).append("\n (1 to 5 stars)");
        String ratingmessage = sb.toString();
        Object newrating = JOptionPane.showInputDialog(this, ratingmessage, "Rate this song!", 2);
    } //GEN-LAST:event_ratesongbuttonActionPerformed

    private void nichebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nichebuttonActionPerformed
        StringBuilder sb = new StringBuilder(currentSongTitle); 
        sb.append(" by ").append(currentArtist).append("\n Nicheness score: ").append("[NICHENESS]");
        String nichemessage = sb.toString();
        JOptionPane.showMessageDialog(this, nichemessage);

    }//GEN-LAST:event_nichebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        setup(loggedUserStr, database);
    }

    /**
     * Reloads window to display new song. Called after every modifying actions (such as viewing new song).
     * @param database
     */
    public void reload(BeMusicDatabase database){
        setDatabase(database);
        
        revalidate();
        repaint();
        System.out.println("\n RELOADED."); 
        String[] song = getInfo(getIndex()); 

        setCurrentDate((song[0]));
        setCurrentUsername((song[1]));
        setCurrentSongTitle((song[2]));
        setCurrentArtist((song[3]));
        
        System.out.println("database" + getDatabase());

        StringBuilder printsong = new StringBuilder("current song: ");
        printsong.append(currentDate).append(currentUsername).append(currentSongTitle).append(currentArtist);
        System.out.println(printsong);
        
        artistlabel.setText(currentArtist);
        songtitlelabel.setText(currentSongTitle);

        StringBuilder sbdate = new StringBuilder("On ");
        sbdate.append(currentDate).append(",");
        String stringdate = sbdate.toString();
        dateplayedlabel.setText(stringdate);

        StringBuilder sbuser = new StringBuilder(currentUsername);
        sbuser.append(" listened to...");
        String stringuser = sbuser.toString();

        userlistenedtext.setText(stringuser);
        getImage(imageUrl);
        
    }
    
    /**
     * First time load process. Initializes TimelineFrame.
     * @param database
     */
    public void firsttimeload(BeMusicDatabase database){
        // here is where we will load the songs from the cvs and process them, with addEntry

        setDatabase(database);
        System.out.println("Adding friends");
        //manually make ppl friends

        database.getUser("pj").addFriend(database.getUser("alyssa"));
        database.getUser("pj").addFriend(database.getUser("cris"));
        /*
        database.getUser("PJ").addFriend(database.getUser("Alyssa"));
        database.getUser("PJ").addFriend(database.getUser("Cris"));
        
        database.getUser("Alyssa").addFriend(database.getUser("Jo"));
        database.getUser("Alyssa").addFriend(database.getUser("Emma"));
        database.getUser("Emma").addFriend(database.getUser("Ethan"));
        database.getUser("Alyssa").addFriend(database.getUser("Aniyah"));
        database.getUser("Alyssa").addFriend(database.getUser("Andrea"));
        database.getUser("Alyssa").addFriend(database.getUser("Hasseit"));
        database.getUser("Alyssa").addFriend(database.getUser("Vanessa"));
        database.getUser("Hasseit").addFriend(database.getUser("Vanessa"));
        database.getUser("Andrea").addFriend(database.getUser("Aniyah"));
        database.getUser("Cris").addFriend(database.getUser("Nelson"));
        database.getUser("Cris").addFriend(database.getUser("Liz"));
        database.getUser("Cris").addFriend(database.getUser("Tomy"));
        database.getUser("Cris").addFriend(database.getUser("Julia"));
        database.getUser("Cris").addFriend(database.getUser("Carmen"));
        database.getUser("Cris").addFriend(database.getUser("Gwyn"));
        database.getUser("Cris").addFriend(database.getUser("Amri"));
        database.getUser("Julia").addFriend(database.getUser("Carmen"));
        database.getUser("Cris").addFriend(database.getUser("Lili"));
        database.getUser("Lili").addFriend(database.getUser("Amri"));
        database.getUser("Nelson").addFriend(database.getUser("Tomy"));
        database.getUser("PJ").addFriend(database.getUser("Aami"));
        database.getUser("PJ").addFriend(database.getUser("Julia"));
        database.getUser("PJ").addFriend(database.getUser("Carmen"));
        database.getUser("PJ").addFriend(database.getUser("Jaden"));
        database.getUser("PJ").addFriend(database.getUser("Rhea"));
        database.getUser("PJ").addFriend(database.getUser("Kieran"));
        database.getUser("PJ").addFriend(database.getUser("Maela"));
        database.getUser("Maela").addFriend(database.getUser("Kieran"));
        database.getUser("Jaden").addFriend(database.getUser("Aami"));
        database.getUser("Jaden").addFriend(database.getUser("Rhea"));
         */
        //TODO edge case if no friends!
        

        System.out.println("database adj list");

        System.out.println(database); //adj list

        System.out.println("userstr" + getLoggedUserStr());
        BeMusicUser loggedUser = database.getUser(loggedUserStr);
        System.out.println("user" + loggedUser);

        ArrayList<String[]> feed = loggedUser.getFeed();

        if (feed.size() == 0){
            addEntry("this day","you have no friends who","You have no friends!", "Hope you find some soon :)", "https://media.tenor.com/t9MWQKc83tgAAAAm/crying-laughing-emoji-gif.webp");
        }

        System.out.println(loggedUserStr + "'s feed...");
        for (String[] post: feed){
            System.out.println("NEW POST:");
            String string = "";
            for (String info:post){
                string = string + info + ", ";
            }
            System.out.println(string);
        }

        setHistory(feed);
        System.out.println("size: " + getHistory().size());

        System.out.println(getHistory().get(0)[0]);
      
        reload(getDatabase());
    }

    /**
     * Sets image for the album cover label.
     * @param link pulled from spotify.
     */
    public void getImage(String link){
        try {
            URL url = new URL(link); 
            Image image = ImageIO.read(url);
            
            Image resized = image.getScaledInstance(250,250,Image.SCALE_DEFAULT);
            imagelabel.setIcon(new ImageIcon(resized));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public static void setup(String loggedUserStr, BeMusicDatabase database){
        
        TimelineFrame timeline = new TimelineFrame(loggedUserStr);
        timeline.setDatabase(database);
        timeline.firsttimeload(database);
        timeline.reload(database);

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> timeline.setVisible(true));
    }
    //modified 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel artistlabel;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel dateplayedlabel;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton lastbutton;
    private javax.swing.JButton nextbutton;
    private javax.swing.JButton nichebutton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton ratesongbutton;
    private javax.swing.JPanel songdisplay;
    private javax.swing.JLabel songtitlelabel;
    private javax.swing.JLabel timelineLabel;
    private javax.swing.JPanel toolbarPanel;
    private javax.swing.JLabel userlistenedtext;
    // End of variables declaration//GEN-END:variables
}
